monitor.alsa.rules = [
  {
    matches = [
      { device.name = "alsa_card.usb-Turtle_Beach_Stealth_Pro_Xbox_5802FFFF5202-01" }
    ]
    actions = {
      update-props = {
        api.alsa.soft-mixer = true
      }
    }
  }
]
