# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

windowrulev2 = workspace 5,class:(thunderbird)
windowrulev2 = monitor 0,class:(thunderbird)
windowrulev2 = workspace 3,class:(discord)
windowrulev2 = monitor 1,class:(discord)
windowrulev2 = workspace 3,class:(signal)
windowrulev2 = monitor 1,class:(signal)
