# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

windowrule = monitor 1, workspace 4, match:class thunderbird
windowrule = monitor 1, workspace 3, match:class discord
windowrule = monitor 1, workspace 3, match:class signal
windowrule = workspace empty, match:class heroic 
windowrule = workspace empty, match:class steam, match:title ^(Sign in to Steam)$
windowrule = workspace unset, match:class steam, match:title negative:^(Sign in to Steam)$
